# Generated by Django 3.2.25 on 2024-06-04 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20240601_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='due_date',
            new_name='start_time',
        ),
    ]
