# Generated by Django 3.2.25 on 2024-06-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_rename_due_date_task_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('all', 'All'), ('current', 'Current'), ('incomplete', 'Incomplete'), ('long-term', 'Long-term')], default='all', max_length=20),
        ),
    ]
