# Generated by Django 3.2.25 on 2024-06-13 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_auto_20240612_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
